name: ebusd
version: "0.76"
slug: ebusd
description: >
  This Add-on runs [ebusd](http://ebusd.eu), a daemon for handling communication with eBUS devices
  connected to a 2-wire bus system (“energy bus” used by numerous heating systems).

  This repository is
  - in a very early stage of development - please leavepull-requests with improvements
  - build from source and may **take several minutes to install**.
  - not yet tested on anything but a RaspberryPi 4 with an [esera ebus koppler](https://www.esera.de/produkte/ebus/135/1-wire-hub-platine)
url: https://github.com/LukasGrebe/ha-addons
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: "system"
boot: "auto"
uart: true
options:
  port: 8888
  mqttport: 0
schema:
  device: "device(subsystem=tty)"
  port: "port?"
  latency: "int(0,10000)?"
  readonly: "bool?"
  foreground: "bool?"
  scanconfig: "bool?"
  logareas: "list(main|network|bus|update|all)?"
  loglevel: "list(error|notice|info|debug)?"
  mqtthost: "str?"
  mqttport: "int?"
  mqttuser: "str?"
  mqttpass: "str?"
  mqttjson: "bool?"
  mqttlog: "bool?"
